import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author MALBUF
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    
    
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        JK = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        tmpLahir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tglLahir = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Print = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        labeljam = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 590, 30);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The Real Informatic Schools");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 50, 240, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ISIAN DATA SISWA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 0, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 250, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);
        jPanel2.add(email);
        email.setBounds(10, 320, 220, 30);
        jPanel2.add(nis);
        nis.setBounds(10, 30, 220, 30);
        jPanel2.add(nama);
        nama.setBounds(10, 80, 220, 30);
        jPanel2.add(kelas);
        kelas.setBounds(10, 270, 220, 30);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 370, 220, 80);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 32, 20);

        JK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JK.setText("Jenis Kelamin");
        jPanel2.add(JK);
        JK.setBounds(10, 210, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 300, 34, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Alamat");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 350, 90, 20);

        buttonGroup1.add(lk);
        lk.setText("Male");
        jPanel2.add(lk);
        lk.setBounds(10, 230, 60, 23);

        buttonGroup1.add(pr);
        pr.setText("Female");
        jPanel2.add(pr);
        pr.setBounds(70, 230, 93, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Kelas");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 250, 50, 20);
        jPanel2.add(tmpLahir);
        tmpLahir.setBounds(10, 130, 220, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tanggal Lahir");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 160, 140, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tempat Lahir");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 110, 140, 20);
        jPanel2.add(tglLahir);
        tglLahir.setBounds(10, 180, 220, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("NIS");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 10, 19, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 130, 250, 460);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel4.add(Print);
        Print.setBounds(530, 20, 70, 30);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel4.add(Save);
        Save.setBounds(40, 20, 70, 30);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel4.add(Delete);
        Delete.setBounds(130, 20, 70, 30);

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel4.add(Clear);
        Clear.setBounds(230, 20, 70, 30);

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel4.add(Refresh);
        Refresh.setBounds(330, 20, 80, 30);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel4.add(Edit);
        Edit.setBounds(430, 20, 70, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(270, 100, 630, 60);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(13, 13, 610, 330);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(270, 160, 630, 430);

        jPanel3.setBackground(new java.awt.Color(232, 64, 43));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        labeljam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setText("JAM");
        jPanel3.add(labeljam);
        labeljam.setBounds(740, 40, 80, 20);

        labeltanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labeltanggal.setForeground(new java.awt.Color(255, 255, 255));
        labeltanggal.setText("TANGGAL");
        jPanel3.add(labeltanggal);
        labeltanggal.setBounds(740, 20, 80, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 910, 100);

        setBounds(0, 0, 925, 629);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(tglLahir.getDate());
       String JK = "";
       
        String Nis = nis.getText();
        String Nama = nama.getText();
        String TmpLahir = tmpLahir.getText();
        String Kelas = kelas.getText();
        String Email = email.getText();
        String Alamat = alamat.getText();
        
        if (lk.isSelected()) {
            JK = "L";
        } else {
            JK = "P";
        }
        
                    
        if(nis.getText().equals("") || 
           nama.getText().equals("") ||
                tmpLahir.getText().equals("") ||
                        tanggal.equals("") ||
                JK.equals("") ||
                kelas.getText().equals("")||
              email.getText().equals("") ||
                alamat.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Harap Lengkai Data", "Error",
                    JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL ="INSERT INTO t_siswa (NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat)" 
                    + "VALUES('"+nis.getText()+"','"+nama.getText()+"','"+tmpLahir.getText()+"','"+tanggal+"','"+JK+"',"
                    + "'"+kelas.getText()+"','"+email.getText()+"','"+alamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:                                     
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_DeleteActionPerformed
    }
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        nis.setText("");
        kelas.setText("");
        buttonGroup1.clearSelection();
        email.setText("");
        alamat.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_RefreshActionPerformed

     private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","TempatLahir","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
            DefaultTableModel dtm = new DefaultTableModel(null, kolom);
            String SQL = "SELECT * FROM t_siswa";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            try{
                while(rs.next()) {
                    String NIS = rs.getString(1);
                    String NamaSiswa = rs.getString(2);
                    String TempatLahir = rs.getString(3);
                    String TanggalLahir = rs.getString(4);
                    String JenisKelamin = "";
                    if ("L".equals(rs.getString(5))){
                        JenisKelamin = "Laki-Laki";
                    }else {
                        JenisKelamin = "Perempuan";
                    }
                    String Kelas = rs.getString(6);
                    String Email = rs.getString(7);
                    String Alamat = rs.getString(8);
                    String data[] = {NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
                    dtm.addRow(data);
                }
            } catch (SQLException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            tblData.setModel(dtm);
        }
//To change body of generated methods, choose Tools | Templates.
    
    
    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new  MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat  footer = new MessageFormat("Page {0,number,integer}        ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            
        }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
              
    }//GEN-LAST:event_PrintActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            nis.setText(tblData.getValueAt(baris, 0).toString());
            nis.setEditable(false);
            nama.setText(tblData.getValueAt(baris,1).toString());
            tmpLahir.setText(tblData.getValueAt(baris, 2).toString());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = tblData.getValueAt(baris, 3).toString();
            Date tgl;
            try {
                tgl = dateFormat.parse(tanggal);
                tglLahir.setDate(tgl);
            }catch (ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null,ex);
            }
            String JK = tblData.getValueAt(baris, 4).toString();
            if (JK.equals("Laki-laki")){
                lk.setSelected(true);
            }else {
                pr.setSelected(true);
            }
            kelas.setText(tblData.getValueAt(baris, 5).toString());
            email.setText(tblData.getValueAt(baris, 6).toString());
            alamat.setText(tblData.getValueAt(baris, 7).toString());
        }
        
        
        
    }//GEN-LAST:event_tblDataMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    
    public void setTanggal(){
           java.util.Date skrg = new java.util.Date();
           java.text.SimpleDateFormat kal = new
            java.text.SimpleDateFormat("dd/MM/yyyy");
           labeltanggal.setText(kal.format(skrg));
       } 
      public void setJam() {
    ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            Date dt = new Date();
            int nilai_jam = dt.getHours();
            int nilai_menit = dt.getMinutes();
            int nilai_detik = dt.getSeconds();
            if(nilai_jam <= 9){
                nol_jam = "0";
            }
            if(nilai_menit <= 9){
                nol_menit = "0";
            }
            if(nilai_detik <= 9){
                nol_detik = "0";
            }
                
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            labeljam.setText("Jam " +jam+ ":" +menit+ ":" +detik);
            
        }
    };
    new Timer(100, taskPerformer).start();
      }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel JK;
    private javax.swing.JButton Print;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kelas;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JRadioButton lk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tglLahir;
    private javax.swing.JTextField tmpLahir;
    // End of variables declaration//GEN-END:variables

}

